### ISSUE TITLE
Add shuttle as part of Rust on Nails

### ISSUE THREAD

**Issue by ivancernja** [purton-tech/rust-on-nails#11]
Hey team,

I'd like to propose adding [shuttle](https://shuttle.rs) as part of Rust on Nails!

In short; shuttle is a Rust-native, open source, cloud development platform that's taking care of all the infrastructure hassle out of the box.

Currently supports deploying:
* axum
* tower
* poem
* rocket
* tide

All it takes is an annotation in your main file and you are good to go!

I'd be happy to provide content for the docs; just shoot me a msg on Discord (dohman#0193) or via [e-mail.](mailto: ivan@shuttle.rs)

https://github.com/shuttle-hq/shuttle/

**Comment by ianpurton** [comment]
@ivancernja A nails app is usually deployed as 2 or more containers as we use https://github.com/purton-tech/barricade for authentication. Can shuttle handle this?

**Comment by ianpurton** [comment]
@ivancernja Closing due to lack of response.
