### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by iodapson** [purton-tech/rust-on-nails#15]
I think as Rust-on-nails becomes more widely known and used, there is a high chance people would have questions or run into issues as they use it. Therefore, I ask that if possible, you can create a nexus hub or community to discuss 'Rust on Nails'. Alternatively, you could join the chat on an already created 'Axum' room on Matrix.

**Comment by ianpurton** [comment]
@iodapson I do have the discussions area here https://github.com/purton-tech/rust-on-nails/discussions

I need to get it linked on the web pages.

**Comment by iodapson** [comment]
Okay, and that would be really nice. 

It seems the setup used in https://cloak.software/blog/rust-on-nails/ is very different from the setup used in https://rust-on-nails.com/ - which is better than the first one. I can shed light on some of the issues I faced with it on the discussions panel.

**Comment by ianpurton** [comment]
@iodapson Discussions are now setup. https://github.com/purton-tech/rust-on-nails/discussions
