### ISSUE TITLE
Update Git version inside container to allow signing with SSH

### ISSUE THREAD

**Issue by farazfazli** [purton-tech/rust-on-nails#40]
Hi Ian,

I feel we should have Git version 2.34 or later in the Rust on Nails Dev Container (we currently have 2.30.2). This would support signing commits with an SSH key. Signing commits is a good practice and maintaining a separate set of keys for authentication and signing (SSH + GPG) seems cumbersome.

As per https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials by default Git SSH keys are forwarded to Dev Containers, so besides updating the Git version nothing else should be required to make this work.

Interested in hearing your thoughts on this.

Sincerely,
Faraz

**Comment by ianpurton** [comment]
Currently I'm inheriting from rust:slim which is at https://hub.docker.com/_/rust

Which using debian bullseye

![image](https://user-images.githubusercontent.com/36966/226271088-ace351f2-148b-45b7-b887-eaba2478ae2e.png)

So the fix is to move up bookworm.

**Comment by farazfazli** [comment]
I don't think it's a good idea to upgrade to Debian Bullseye just because of one package - especially given that Bullseye isn't stable yet. Best strategy here in my opinion would be to use a backport. I've opened a pull request linked to this issue which adds the backport, thus installing Git version 2.39.2.

Let me know your thoughts on this approach. Thanks.
