### ISSUE TITLE
guide: first dbmate migration does not produce a schema.sql

### ISSUE THREAD

**Issue by austinmilt** [purton-tech/rust-on-nails#60]
I'm following the rust on nails guide and noticed that running the [first migration](https://rust-on-nails.com/docs/database-part-1/database-migrations/) does not produce a `schema.sql`. As a relative beginner I am wondering if that's expected (and thus the guide should change) or if it's indicative of some other issue. Here's a record:

```bash
/workspace/crates/db (main) 
$ dbmate status
[ ] 20240125025702_user_tables.sql

Applied: 0
Pending: 1
/workspace/crates/db (main) 
$ dbmate up
Applying: 20240125025702_user_tables.sql
/workspace/crates/db (main) 
$ dbmate status
[X] 20240125025702_user_tables.sql

Applied: 1
Pending: 0
/workspace/crates/db (main) 
$ psql $DATABASE_URL -c 'SELECT count(*) FROM users;'
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
 count 
-------
     3
(1 row)
/workspace/crates/db (main) 
$ ls
Cargo.toml  migrations  queries  src
```

**Comment by austinmilt** [comment]
Also note the separate undocumented issue about supplying locale settings.

**Comment by JoshuaMichaelHanson** [comment]
I also noticed this, but seems to work OK.  Also noticed that the website was updated today while I was following the tutorial ;)  Created the axum-server and next page it was the web-ui. Not a big deal also a couple other issues I was going to report were fixed so kudos on the update.  Please let us know if the schema.sql is required or if the docs just need to be updated.

**Comment by 9876691** [comment]
Hi, The docs do need to be updated.

I'm re-writing the whole guide to fix as many issues as I can.
