### ISSUE TITLE
guide: cache busting page missing information

### ISSUE THREAD

**Issue by t3chnicallyinclined** [purton-tech/rust-on-nails#62]
Hello, I am following the rust on nails guide and am trying to implement the cache busting part here https://rust-on-nails.com/docs/full-stack-web/cache-busting/

one question I have is the code here, there is no cornucopia function defined, also confused as I thought cornucopia is used for sql function generation. 

```
fn main() -> Result<()>  {

    cornucopia()?;

    let mut ructe = Ructe::from_env().unwrap();
    let mut statics = ructe.statics().unwrap();
    statics.add_files("dist").unwrap();
    statics.add_files("images").unwrap();
    ructe.compile_templates("templates").unwrap();

    Ok(())
}
```

Also there is a reference to:

`use assets::templates::statics::StaticFile; ` 

Which in the guide provides code to update the axum server with the following function:

```
async fn static_path(Path(path): Path<String>) -> impl IntoResponse {
    let path = path.trim_start_matches('/');

    if let Some(data) = StaticFile::get(path) {
        Response::builder()
            .status(StatusCode::OK)
            .header(
                header::CONTENT_TYPE,
                HeaderValue::from_str(data.mime.as_ref()).unwrap(),
            )
            .body(body::boxed(Body::from(data.content)))
            .unwrap()
    } else {
        Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(body::boxed(Empty::new()))
            .unwrap()
    }
}
```

However there is no  `assets::templates::statics::StaticFile::get` defined in the guide. 

How should I proceed with this? did I miss something ?

**Comment by t3chnicallyinclined** [comment]
hello @roger-maddocks 

Yes, I went to their other repositories that have more complete code to figure out how it should be working. 

These repositories use the same framework, and should give you a good idea of how it should look when complete. 

https://github.com/bionic-gpt/bionic-gpt/blob/main/crates/asset-pipeline/build.rs
https://github.com/purton-tech/barricade/blob/master/crates/asset-pipeline/build.rs
https://github.com/purton-tech/cloak/blob/main/crates/asset-pipeline/build.rs

**Comment by roger-maddocks** [comment]
@t3chnicallyinclined super helpful, great idea. Thank you!
