### ISSUE TITLE
Cannot build `crates/db/src/lib.rs` 

### ISSUE THREAD

**Issue by 000sub** [purton-tech/rust-on-nails#64]
https://rust-on-nails.com/docs/database-part-1/database-access/

I followed above tutorial and faced this error.

_use rustls::client::danger::{ServerCertVerified, ServerCertVerifier, HandshakeSignatureValid};_

This import snippet doesn't work in rustls@0.21.10 version.

I've already tried to re-import each structs but it shows me different traits.

Is there any updated version of `lib.rs` file?

**Comment by 9876691** [comment]
This should now be fixed.
